replicaCount: 1

image:
  repository: ghcr.io/noone-home/chatgpt-discord-bot
  tag: 1.0.0
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-secret

container:
  name: chatgpt-discord-bot
  envFile: .env
  restartPolicy: Always

envConfig: |
  # Discord Bot token https://discord.com/developers/applications
  DISCORD_BOT_TOKEN=

  LOGGING=True
  REPLYING_ALL=False

  # channel using to send the starting-prompt
  DISCORD_CHANNEL_ID=
  REPLYING_ALL_DISCORD_CHANNEL_ID=

  # cookies for generating images
  BING_COOKIE=      # https://www.bing.com/chat -> _U
  GOOGLE_PSID=      # https://gemini.google.com/app -> __Secure-1PSID

  # OpenAI API-key -> https://platform.openai.com/api-keys
  OPENAI_ENABLED=True
  OPENAI_KEY=
  OPENAI_TEMPERTUARES=0.5

  # Default Model
  MODEL=gpt-3.5-turbo

resources: {}
