name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chatgpt-discord-bot:1.0.0
      
    - name: TagImage
      run: |
        docker login ghcr.io -u joaodss2 -p ${{ secrets.GHDOCKERREPOSITORYTOKEN }}
        
        docker tag chatgpt-discord-bot:1.0.0 ghcr.io/noone-home/chatgpt-discord-bot:1.0.0
        docker push ghcr.io/noone-home/chatgpt-discord-bot:1.0.0